name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}" -o devswitch-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}" -o devswitch-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}" -o devswitch-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}" -o devswitch-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}" -o devswitch-windows-amd64.exe .
        
        # Make binaries executable
        chmod +x devswitch-*

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          devswitch-linux-amd64
          devswitch-linux-arm64
          devswitch-darwin-amd64
          devswitch-darwin-arm64
          devswitch-windows-amd64.exe
        body: |
          ## DevSwitch ${{ steps.get_version.outputs.VERSION }}
          
          ### 🎉 New Release Features
          
          - Beautiful CLI with styled boxes and progress bars
          - Instant profile switching for developer configurations
          - Automatic backup and rollback system
          - Profile comparison and selective apply
          - Template system for quick profile creation
          - Extended configuration support (SSH, AWS, Docker, NPM, etc.)
          
          ### 📥 Installation
          
          Download the appropriate binary for your platform and add it to your PATH:
          
          ```bash
          # macOS (Apple Silicon)
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/devswitch-darwin-arm64 -o devswitch
          
          # macOS (Intel)
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/devswitch-darwin-amd64 -o devswitch
          
          # Linux (x64)
          curl -L https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.VERSION }}/devswitch-linux-amd64 -o devswitch
          
          # Make executable and install
          chmod +x devswitch
          sudo mv devswitch /usr/local/bin/
          ```
          
          ### 🚀 Quick Start
          
          ```bash
          # Create your first profile
          devswitch create work
          
          # Create from template
          devswitch create personal --template personal
          
          # Switch profiles
          devswitch apply work
          ```
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}